# Generated by Django 4.1.7 on 2023-03-20 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("name", models.CharField(max_length=50)),
                ("checking_date", models.DateField(default=datetime.datetime.now)),
                ("checkout_date", models.DateField()),
                ("room", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=15)),
            ],
        ),
    ]
