# Generated by Django 4.1.7 on 2023-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking_detail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
