# Generated by Django 4.1.7 on 2023-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_detail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking_detail",
            name="checking_date",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="booking_detail",
            name="checkout_date",
            field=models.CharField(max_length=50),
        ),
    ]
